# Generated by Django 3.0.2 on 2020-02-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200213_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmeta',
            old_name='created',
            new_name='started',
        ),
        migrations.RemoveField(
            model_name='taskmeta',
            name='locked_at',
        ),
    ]
