# Generated by Django 3.0.2 on 2020-01-28 20:16

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('mask', models.CharField(max_length=4, null=True)),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=128)),
                ('subtype', models.CharField(max_length=128)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_iso_currency_code', models.CharField(max_length=3)),
                ('balance_unofficial_currency_code', models.CharField(max_length=3)),
                ('institution_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creds', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_pull', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=255, null=True)),
                ('transaction_type', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iso_currency_code', models.CharField(max_length=3, null=True)),
                ('unofficial_currency_code', models.CharField(max_length=3, null=True)),
                ('date', models.DateField()),
                ('authorized_date', models.DateField()),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('payment_meta', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('payment_channel', models.CharField(max_length=8)),
                ('pending', models.BooleanField()),
                ('pending_transaction_id', models.CharField(max_length=128, null=True)),
                ('account_owner', models.CharField(max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='score.Account')),
                ('transfer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='score.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=128, null=True)),
                ('rent_asked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicant_name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('waiting_for_applicant', 'waiting for applicant'), ('running', 'running'), ('waiting_for_payment', 'waiting for payment'), ('completed', 'completed')], default='waiting_for_applicant', max_length=21)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='score.Item')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='score.Property')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='score.Item'),
        ),
    ]
