# Generated by Django 3.0.2 on 2020-01-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20200128_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='creds',
        ),
        migrations.AddField(
            model_name='item',
            name='access_token',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='last_pull',
            field=models.DateField(auto_now_add=True),
        ),
    ]
