# Generated by Django 3.0.2 on 2020-01-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_auto_20200131_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_iso_currency_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_unofficial_currency_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
