# Generated by Django 3.0.2 on 2020-01-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_auto_20200131_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='authorized_date',
            field=models.DateField(null=True),
        ),
    ]
