# Generated by Django 3.0.2 on 2020-02-07 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_auto_20200131_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='score.Application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('waiting_for_applicant', 'waiting for applicant'), ('running', 'running'), ('payment_pending', 'payment pending'), ('completed', 'completed')], default='waiting_for_applicant', max_length=21),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=128),
        ),
    ]
