# Generated by Django 3.0.2 on 2020-02-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0008_auto_20200207_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rent_asked',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='unit',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
