# Generated by Django 3.0.2 on 2020-02-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0009_auto_20200207_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='state',
        ),
        migrations.AddField(
            model_name='application',
            name='charged_client',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='pulled_plaid_data',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='sent_email_to_applicant',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='rent_asked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='unit',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
