# Generated by Django 3.0.2 on 2020-02-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0010_auto_20200207_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_connected_to_plaid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
