# Generated by Django 3.0.2 on 2020-02-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0011_application_applicant_connected_to_plaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_connected_to_plaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='charged_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='pulled_plaid_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='sent_email_to_applicant',
            field=models.BooleanField(default=False),
        ),
    ]
