# Generated by Django 3.0.2 on 2020-02-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0012_auto_20200207_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sent_email_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
