# Generated by Django 3.0.2 on 2020-02-11 22:23

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0014_auto_20200211_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='access_token',
            field=django_cryptography.fields.encrypt(models.CharField(default='', max_length=128)),
            preserve_default=False,
        ),
    ]
