# Generated by Django 3.0.2 on 2020-02-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0016_encrypt_access_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='old_access_token',
        ),
    ]
