# Generated by Django 3.0.2 on 2020-02-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0017_remove_item_old_access_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='property',
            new_name='user_property',
        ),
    ]
